# Generated by Django 3.1.2 on 2021-03-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_pack',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
