# Generated by Django 3.1.2 on 2021-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_food_pack_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_pack',
            name='available_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
