# Generated by Django 3.1.2 on 2021-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_food_pack_available_for_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_pack',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
