# Generated by Django 3.1.2 on 2021-03-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
