# Generated by Django 3.1.2 on 2021-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20210320_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
